import { NextResponse } from 'next/server';
import { getSupabase, SCREENSHOT_BUCKET } from '@/app/lib/supabase';
import { lookupSiteByUrl } from '@/app/lib/site-lookup';

const GITHUB_TOKEN = process.env.GITHUB_TOKEN!;

const AI_EDIT_WORKFLOW_PATH = '.github/workflows/ai-edit.yml';
const AI_EDIT_BRANCH_PREFIX = 'ai-edit/';

const AI_EDIT_WORKFLOW_YAML = `name: AI Edit
on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Target branch for AI edits'
        required: true
        type: string
      default_branch:
        description: 'Repository default branch'
        required: true
        type: string
      is_iteration:
        description: 'Whether this run is an iteration'
        required: false
        type: string
      previous_summary:
        description: 'Summary of previous AI edits'
        required: false
        type: string
      requirements:
        description: 'User requirements (natural language)'
        required: true
        type: string
      screenshot_url:
        description: 'Public URL of reference screenshot'
        required: false
        type: string

jobs:
  ai-edit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: \${{ secrets.PERSONAL_TOKEN }}
          ref: \${{ inputs.default_branch }}
          fetch-depth: 0

      - name: Prepare branch
        env:
          BRANCH_NAME: \${{ inputs.branch_name }}
          DEFAULT_BRANCH: \${{ inputs.default_branch }}
        run: |
          git fetch origin "$DEFAULT_BRANCH" "$BRANCH_NAME" || true
          if git show-ref --verify --quiet "refs/remotes/origin/$BRANCH_NAME"; then
            git checkout -B "$BRANCH_NAME" "origin/$BRANCH_NAME"
          else
            git checkout -B "$BRANCH_NAME" "origin/$DEFAULT_BRANCH"
          fi

      - name: Download screenshot
        if: \${{ inputs.screenshot_url != '' }}
        run: |
          mkdir -p .ai-edit
          curl -L -o .ai-edit/screenshot.png "\${{ inputs.screenshot_url }}"

      - name: Run Claude Code
        uses: anthropics/claude-code-base-action@beta
        env:
          ANTHROPIC_API_KEY: \${{ secrets.OPENROUTER_API_KEY }}
          ANTHROPIC_BASE_URL: https://openrouter.ai/api
        with:
          model: anthropic/claude-sonnet-4-5
          allowed_tools: Read,Write,Edit,Glob,Grep,Bash
          max_turns: '30'
          prompt: |
            You are editing a Klook microsite repository to fulfill the user's request.

            \${{ inputs.is_iteration == 'true' && 'This is an iteration on an existing AI edit branch. Keep previously approved changes unless the new requirements explicitly override them.' || 'This is the first iteration for this AI edit request.' }}

            \${{ inputs.previous_summary != '' && format('Previous change summary:\\n{0}\\n', inputs.previous_summary) || '' }}

            User requirements (latest):
            \${{ inputs.requirements }}

            \${{ inputs.screenshot_url && 'A reference screenshot is at .ai-edit/screenshot.png — read it with the Read tool to understand the visual context.' || '' }}

            Rules:
            - Modify only files under app/, components/, src/, styles/, public/, content/, or top-level config files like tailwind.config.* and next.config.*
            - Do NOT modify .github/, package.json dependencies, or any workflow files
            - Do NOT modify or delete the .ai-edit/ directory
            - Keep changes minimal and focused on the user's request
            - Preserve existing i18n keys; add new ones if needed
            - When unsure about a file's purpose, use Glob/Grep to explore before editing

      - name: Commit and push
        env:
          BRANCH_NAME: \${{ inputs.branch_name }}
        run: |
          git config user.name "AI Edit Bot"
          git config user.email "ai-edit@klook.com"
          rm -rf .ai-edit
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            REQ_SUMMARY=$(echo "\${{ inputs.requirements }}" | tr '\\n' ' ' | cut -c1-60)
            git commit -m "AI edit: $REQ_SUMMARY"
            git push origin "HEAD:$BRANCH_NAME"
          else
            echo "No changes produced by AI"
            exit 1
          fi

      - name: Ensure PR exists
        env:
          GH_TOKEN: \${{ secrets.PERSONAL_TOKEN }}
          BRANCH_NAME: \${{ inputs.branch_name }}
          DEFAULT_BRANCH: \${{ inputs.default_branch }}
        run: |
          gh pr view "$BRANCH_NAME" --json number >/dev/null 2>&1 && exit 0
          REQ_SUMMARY=$(echo "\${{ inputs.requirements }}" | tr '\\n' ' ' | cut -c1-80)
          gh pr create \
            --base "$DEFAULT_BRANCH" \
            --head "$BRANCH_NAME" \
            --title "AI edit: $REQ_SUMMARY" \
            --body "$(cat <<'EOF'
          Auto-generated by microsite-admin AI edit.

          Latest requirements:
          \${{ inputs.requirements }}
          EOF
          )"
`;

interface EditRequestBody {
  repo?: string;
  pageUrl: string;
  requirements: string;
  areaDescription?: string;
  previousSummary?: string;
}

function composeRequirements(input: { pageUrl: string; areaDescription?: string; change: string }): string {
  const parts: string[] = [];
  parts.push(`Target page URL: ${input.pageUrl}`);
  parts.push('');
  parts.push(
    `The user wants to modify the page served at the URL above. The repository is the Next.js source (not a built site) — locate the route/file in this repo that corresponds to this URL by examining the app/ directory and any i18n routing, then make the change there.`
  );
  if (input.areaDescription?.trim()) {
    parts.push('');
    parts.push(`Area on the page to change: ${input.areaDescription.trim()}`);
  }
  parts.push('');
  parts.push(`Change requested: ${input.change.trim()}`);
  return parts.join('\n');
}

interface PullRequestSummary {
  number: number;
  html_url: string;
  head: { ref: string };
  body: string | null;
}

async function githubApi(endpoint: string, options: RequestInit = {}) {
  const res = await fetch(`https://api.github.com${endpoint}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${GITHUB_TOKEN}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

  const data = await res.json().catch(() => ({}));
  if (!res.ok) {
    const err = new Error(`GitHub API error: ${res.status} - ${data.message || JSON.stringify(data)}`);
    (err as Error & { status?: number }).status = res.status;
    throw err;
  }
  return data;
}

async function ensureWorkflowFile(repoFullName: string) {
  let existingSha: string | undefined;
  try {
    const existing = await githubApi(`/repos/${repoFullName}/contents/${AI_EDIT_WORKFLOW_PATH}`);
    existingSha = existing.sha;
  } catch (e: unknown) {
    const status = (e as Error & { status?: number }).status;
    if (status !== 404) throw e;
  }

  const content = Buffer.from(AI_EDIT_WORKFLOW_YAML).toString('base64');
  await githubApi(`/repos/${repoFullName}/contents/${AI_EDIT_WORKFLOW_PATH}`, {
    method: 'PUT',
    body: JSON.stringify({
      message: existingSha ? 'Update AI edit workflow' : 'Add AI edit workflow',
      content,
      ...(existingSha && { sha: existingSha }),
    }),
  });
}

async function getDefaultBranch(repoFullName: string): Promise<string> {
  const data = await githubApi(`/repos/${repoFullName}`);
  return data.default_branch || 'main';
}

async function findOpenAiEditPr(repoFullName: string): Promise<PullRequestSummary | null> {
  const pulls = await githubApi(`/repos/${repoFullName}/pulls?state=open&per_page=30`);
  const list = Array.isArray(pulls) ? pulls : [];
  const matched = list.find((pr: PullRequestSummary) => pr?.head?.ref?.startsWith(AI_EDIT_BRANCH_PREFIX));
  return matched || null;
}

async function hasRunningAiEditRun(repoFullName: string): Promise<boolean> {
  const runs = await githubApi(`/repos/${repoFullName}/actions/workflows/ai-edit.yml/runs?per_page=10`);
  const workflowRuns = runs.workflow_runs || [];
  return workflowRuns.some((run: { status: string }) => run.status !== 'completed');
}

export async function POST(request: Request) {
  try {
    if (!GITHUB_TOKEN) {
      return NextResponse.json({ error: 'GITHUB_TOKEN not configured' }, { status: 500 });
    }

    const formData = await request.formData();
    const body: EditRequestBody = {
      repo: (formData.get('repo') as string) || undefined,
      pageUrl: (formData.get('pageUrl') as string) || '',
      requirements: (formData.get('requirements') as string) || '',
      areaDescription: (formData.get('areaDescription') as string) || undefined,
      previousSummary: (formData.get('previousSummary') as string) || undefined,
    };
    const screenshotFile = formData.get('screenshot') as File | null;

    if (!body.pageUrl?.trim() || !body.requirements?.trim()) {
      return NextResponse.json({ error: 'Missing required fields: pageUrl and requirements' }, { status: 400 });
    }

    // Resolve repo from pageUrl if not provided
    let repo = body.repo;
    if (!repo) {
      const site = await lookupSiteByUrl(body.pageUrl);
      if (!site) {
        return NextResponse.json({ error: `No site found matching URL: ${body.pageUrl}` }, { status: 404 });
      }
      repo = site.repo_full_name;
    }

    const composedRequirements = composeRequirements({
      pageUrl: body.pageUrl.trim(),
      areaDescription: body.areaDescription,
      change: body.requirements,
    });

    if (screenshotFile) {
      if (!screenshotFile.type.startsWith('image/')) {
        return NextResponse.json({ error: 'Screenshot must be an image file' }, { status: 400 });
      }
      if (screenshotFile.size > 5 * 1024 * 1024) {
        return NextResponse.json({ error: 'Screenshot too large (max 5MB)' }, { status: 400 });
      }
    }

    let screenshotUrl: string | undefined;
    if (screenshotFile) {
      try {
        const supabase = getSupabase();
        const ext = screenshotFile.name.split('.').pop() || 'png';
        const objectPath = `${repo.replace('/', '-')}-${Date.now()}.${ext}`;
        const { error: uploadError } = await supabase.storage
          .from(SCREENSHOT_BUCKET)
          .upload(objectPath, screenshotFile, {
            contentType: screenshotFile.type,
            cacheControl: '3600',
            upsert: false,
          });
        if (uploadError) throw uploadError;
        const { data } = supabase.storage.from(SCREENSHOT_BUCKET).getPublicUrl(objectPath);
        screenshotUrl = data.publicUrl;
      } catch (e: unknown) {
        const msg = e instanceof Error ? e.message : String(e);
        return NextResponse.json({
          error: `Screenshot upload failed (Supabase): ${msg}. Verify SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY and that the "${SCREENSHOT_BUCKET}" bucket exists.`
        }, { status: 500 });
      }
    }

    // Mark site as editing in DB (best-effort; ignore if not in DB)
    try {
      const supabase = getSupabase();
      await supabase
        .from('sites')
        .update({ status: 'editing' })
        .eq('repo_full_name', repo);
    } catch {
      // Site may pre-date DB tracking; continue
    }

    await ensureWorkflowFile(repo);

    const defaultBranch = await getDefaultBranch(repo);
    const existingPr = await findOpenAiEditPr(repo);
    const branchName = existingPr?.head?.ref || `${AI_EDIT_BRANCH_PREFIX}${Date.now().toString(36)}`;
    const isIteration = Boolean(existingPr);
    const previousSummary = body.previousSummary?.trim() || existingPr?.body || '';

    if (isIteration && (await hasRunningAiEditRun(repo))) {
      return NextResponse.json({
        error: 'An AI edit run is still in progress for this repository. Please wait for it to finish before refining again.',
      }, { status: 409 });
    }

    await new Promise(resolve => setTimeout(resolve, 1500));

    await githubApi(`/repos/${repo}/actions/workflows/ai-edit.yml/dispatches`, {
      method: 'POST',
      body: JSON.stringify({
        ref: defaultBranch,
        inputs: {
          branch_name: branchName,
          default_branch: defaultBranch,
          is_iteration: isIteration ? 'true' : 'false',
          previous_summary: previousSummary,
          requirements: composedRequirements,
          screenshot_url: screenshotUrl ?? '',
        },
      }),
    });

    await new Promise(resolve => setTimeout(resolve, 2000));
    let runUrl = `https://github.com/${repo}/actions`;
    try {
      const runs = await githubApi(`/repos/${repo}/actions/runs?per_page=1`);
      if (runs.workflow_runs?.length > 0) {
        runUrl = runs.workflow_runs[0].html_url;
      }
    } catch {
      // not critical
    }

    return NextResponse.json({
      repoFullName: repo,
      runUrl,
      branchName,
      prNumber: existingPr?.number ?? null,
      prUrl: existingPr?.html_url ?? null,
      screenshotUrl,
      isIteration,
      message: 'AI edit workflow dispatched',
    });
  } catch (e: unknown) {
    const message = e instanceof Error ? e.message : 'Unknown error';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
